version: v2beta1
name: summerang

pipelines:
  dev:
    run: |-
      run_dependencies --all
      ensure_pull_secrets --all
      create_deployments --all
      start_dev aspapp
  deploy:
    run: |-
      run_dependencies --all  
      ensure_pull_secrets --all                         
      build_images --all    
      create_deployments --all                          

deployments:
  cert-manager:
    namespace: telemetry
    helm:
      chart:
        name: cert-manager
        repo: https://charts.jetstack.io
      valuesFiles: ["helm-values/cert-manager.yaml"]
      
  opentelemetry-operator:
    namespace: telemetry
    helm:
      chart:
        name: opentelemetry-operator
        repo: https://open-telemetry.github.io/opentelemetry-helm-charts
      valuesFiles: ["helm-values/open-telemetry-operator.yaml"]

        #  opentelemetry-instrumentation:
        #    namespace: telemetry
        #    kubectl:
        #      manifests: ["kubernetes-manifests/open-telemetry-instrumentation.yaml"]

  opentelemetry-collector:
    namespace: telemetry
    helm:
      chart:
        name: opentelemetry-collector
        repo: https://open-telemetry.github.io/opentelemetry-helm-charts
      valuesFiles: ["helm-values/open-telemetry-collector.yaml"]

  loki-stack:
    namespace: telemetry
    helm:
      chart:
        name: loki-stack
        repo: https://grafana.github.io/helm-charts
      valuesFiles: ["helm-values/loki-stack.yaml"]

localRegistry:
  enabled: true
  name: registry
  namespace: images
