apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otelins
  namespace: telemetry
spec:
  exporter:
    endpoint: otelcol-opentelemetry-collector:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  env:
    dotnet:
        OTEL_LOG_LEVEL: debug

